/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.libpasta;

public class Bcrypt extends PrimitiveWrapper {
  private transient long swigCPtr;

  protected Bcrypt(long cPtr, boolean cMemoryOwn) {
    super(pastaJNI.Bcrypt_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Bcrypt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pastaJNI.delete_Bcrypt(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Bcrypt() {
    this(pastaJNI.new_Bcrypt__SWIG_0(), true);
  }

  public Bcrypt(int cost) {
    this(pastaJNI.new_Bcrypt__SWIG_1(cost), true);
  }

}
