/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.libpasta;

public class Config {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Config(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Config obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pastaJNI.delete_Config(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Config() {
    this(pastaJNI.new_Config__SWIG_0(), true);
  }

  public Config(PrimitiveWrapper p) {
    this(pastaJNI.new_Config__SWIG_1(PrimitiveWrapper.getCPtr(p), p), true);
  }

  public static Config with_primitive(PrimitiveWrapper p) {
    long cPtr = pastaJNI.Config_with_primitive(PrimitiveWrapper.getCPtr(p), p);
    return (cPtr == 0) ? null : new Config(cPtr, false);
  }

  public String hash_password(String password) {
    return pastaJNI.Config_hash_password(swigCPtr, this, password);
  }

  public HashUpdate migrate_hash(String hash) {
    long cPtr = pastaJNI.Config_migrate_hash(swigCPtr, this, hash);
    return (cPtr == 0) ? null : new HashUpdate(cPtr, false);
  }

  public boolean verify_password(String hash, String password) {
    return pastaJNI.Config_verify_password(swigCPtr, this, hash, password);
  }

  public HashUpdate verify_password_update_hash(String hash, String password) {
    long cPtr = pastaJNI.Config_verify_password_update_hash(swigCPtr, this, hash, password);
    return (cPtr == 0) ? null : new HashUpdate(cPtr, false);
  }

}
