/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.libpasta;

public class pasta {
  public static HashUpdate migrate_hash(String hash) {
    long cPtr = pastaJNI.migrate_hash(hash);
    return (cPtr == 0) ? null : new HashUpdate(cPtr, true);
  }

  public static HashUpdate verify_password_update_hash(String hash, String password) {
    long cPtr = pastaJNI.verify_password_update_hash(hash, password);
    return (cPtr == 0) ? null : new HashUpdate(cPtr, true);
  }

  public static String hash_password(String password) {
    return pastaJNI.hash_password(password);
  }

  public static String read_password(String prompt) {
    return pastaJNI.read_password(prompt);
  }

  public static boolean verify_password(String hash, String password) {
    return pastaJNI.verify_password(hash, password);
  }

}
