/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package io.github.libpasta;

import org.scijava.nativelib.*;

public class pastaJNI {

  static {
    try {
        NativeLibraryUtil.loadNativeLibrary(pastaJNI.class, "pasta_jni");
    } catch (Exception e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native String hash_password(String jarg1);
  public final static native boolean verify_password(String jarg1, String jarg2);
  public final static native void free_string(String jarg1);
  public final static native String read_password(String jarg1);
}
