/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.libpasta;

public class PrimitiveWrapper {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PrimitiveWrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrimitiveWrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pastaJNI.delete_PrimitiveWrapper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_Primitive inner() {
    long cPtr = pastaJNI.PrimitiveWrapper_inner(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Primitive(cPtr, false);
  }

}
