/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.libpasta;

public class ResultHash {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ResultHash(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResultHash obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pastaJNI.delete_ResultHash(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ResultHash() {
    this(pastaJNI.new_ResultHash__SWIG_0(), true);
  }

  public ResultHash(boolean first, String second) {
    this(pastaJNI.new_ResultHash__SWIG_1(first, second), true);
  }

  public ResultHash(ResultHash p) {
    this(pastaJNI.new_ResultHash__SWIG_2(ResultHash.getCPtr(p), p), true);
  }

  public void setFirst(boolean value) {
    pastaJNI.ResultHash_first_set(swigCPtr, this, value);
  }

  public boolean getFirst() {
    return pastaJNI.ResultHash_first_get(swigCPtr, this);
  }

  public void setSecond(String value) {
    pastaJNI.ResultHash_second_set(swigCPtr, this, value);
  }

  public String getSecond() {
    return pastaJNI.ResultHash_second_get(swigCPtr, this);
  }

}
