/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.libpasta;

public class Scrypt extends PrimitiveWrapper {
  private transient long swigCPtr;

  protected Scrypt(long cPtr, boolean cMemoryOwn) {
    super(pastaJNI.Scrypt_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Scrypt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pastaJNI.delete_Scrypt(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Scrypt() {
    this(pastaJNI.new_Scrypt__SWIG_0(), true);
  }

  public Scrypt(short log_n, long r, long p) {
    this(pastaJNI.new_Scrypt__SWIG_1(log_n, r, p), true);
  }

}
